# Generated by Django 5.0.7 on 2024-08-13 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['product_name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='products',
            name='comment_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество опубликованных комментариев'),
        ),
        migrations.AddField(
            model_name='products',
            name='order_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заказов'),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Слаг - это часть URL-адреса ресурса', max_length=255, unique=True, verbose_name='Слаг категории'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(help_text='Слаг - это часть URL-адреса ресурса', max_length=255, unique=True, verbose_name='Слаг'),
        ),
    ]
